config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :recipe_types
  resources :authors
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  before_action :set_recipe_type, only: %i[ show edit update destroy ]

  # GET /recipe_types or /recipe_types.json
  def index
    @recipe_types = RecipeType.all
  end

  # GET /recipe_types/1 or /recipe_types/1.json
  def show
  end

  # GET /recipe_types/new
  def new
    @recipe_type = RecipeType.new
  end

  # GET /recipe_types/1/edit
  def edit
  end

  # POST /recipe_types or /recipe_types.json
  def create
    @recipe_type = RecipeType.new(recipe_type_params)

    respond_to do |format|
      if @recipe_type.save
        format.html { redirect_to @recipe_type, notice: "Recipe type was successfully created." }
        format.json { render :show, status: :created, location: @recipe_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_types/1 or /recipe_types/1.json
  def update
    respond_to do |format|
      if @recipe_type.update(recipe_type_params)
        format.html { redirect_to @recipe_type, notice: "Recipe type was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_types/1 or /recipe_types/1.json
  def destroy
    @recipe_type.destroy
    respond_to do |format|
      format.html { redirect_to recipe_types_url, notice: "Recipe type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_type
      @recipe_type = RecipeType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_type_params
      params.require(:recipe_type).permit(:name, :description)
    end
end

app/helpers/recipe_types_helper.rb
module RecipeTypesHelper
end

app/views/recipe_types/_form.html.erb
<%= form_with(model: recipe_type) do |form| %>
  <% if recipe_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe_type.errors.count, "error") %> prohibited this recipe_type from being saved:</h2>

      <ul>
        <% recipe_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_types/edit.html.erb
<h1>Editing Recipe Type</h1>

<%= render 'form', recipe_type: @recipe_type %>

<%= link_to 'Show', @recipe_type %> |
<%= link_to 'Back', recipe_types_path %>

app/views/recipe_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipe Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_types.each do |recipe_type| %>
      <tr>
        <td><%= recipe_type.name %></td>
        <td><%= recipe_type.description %></td>
        <td><%= link_to 'Show', recipe_type %></td>
        <td><%= link_to 'Edit', edit_recipe_type_path(recipe_type) %></td>
        <td><%= link_to 'Destroy', recipe_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe Type', new_recipe_type_path %>

app/views/recipe_types/new.html.erb
<h1>New Recipe Type</h1>

<%= render 'form', recipe_type: @recipe_type %>

<%= link_to 'Back', recipe_types_path %>

app/views/recipe_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe_type.description %>
</p>

<%= link_to 'Edit', edit_recipe_type_path(@recipe_type) %> |
<%= link_to 'Back', recipe_types_path %>